import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer.js'
import Navbar from '../components/Navbar.js'
import styles from '../styles/Home.module.css'
import Link from "next/link"
// import Image from 'next/image'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Coffeex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      
      <div>
       <img className='object-cover h-[96vh] w-screen' src='/coffee.jpg' alt=''/>

      </div>
      
    </div>
  )
}
